// Comprehensive list of world languages for the language selector.
export const WORLD_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'it', name: 'Italiano (Italian)' },
  { code: 'pt', name: 'Português (Portuguese)' },
  { code: 'pt-BR', name: 'Português Brasileiro' },
  { code: 'nl', name: 'Nederlands (Dutch)' },
  { code: 'ru', name: 'Русский (Russian)' },
  { code: 'uk', name: 'Українська (Ukrainian)' },
  { code: 'pl', name: 'Polski (Polish)' },
  { code: 'cs', name: 'Čeština (Czech)' },
  { code: 'sk', name: 'Slovenčina (Slovak)' },
  { code: 'hu', name: 'Magyar (Hungarian)' },
  { code: 'ro', name: 'Română (Romanian)' },
  { code: 'bg', name: 'Български (Bulgarian)' },
  { code: 'sr', name: 'Српски (Serbian)' },
  { code: 'hr', name: 'Hrvatski (Croatian)' },
  { code: 'sl', name: 'Slovenščina (Slovenian)' },
  { code: 'el', name: 'Ελληνικά (Greek)' },
  { code: 'tr', name: 'Türkçe (Turkish)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'he', name: 'עברית (Hebrew)' },
  { code: 'fa', name: 'فارسی (Persian)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'ml', name: 'മലയാളം (Malayalam)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'th', name: 'ไทย (Thai)' },
  { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Bahasa Melayu (Malay)' },
  { code: 'tl', name: 'Filipino (Tagalog)' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'ko', name: '한국어 (Korean)' },
  { code: 'zh', name: '中文 (Chinese Simplified)' },
  { code: 'zh-TW', name: '繁體中文 (Chinese Traditional)' },
  { code: 'yue', name: '粵語 (Cantonese)' },
  { code: 'km', name: 'ខ្មែរ (Khmer)' },
  { code: 'lo', name: 'ລາວ (Lao)' },
  { code: 'my', name: 'မြန်မာ (Burmese)' },
  { code: 'si', name: 'සිංහල (Sinhala)' },
  { code: 'ne', name: 'नेपाली (Nepali)' },
  { code: 'am', name: 'አማርኛ (Amharic)' },
  { code: 'sw', name: 'Kiswahili (Swahili)' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'ha', name: 'Hausa' },
  { code: 'ig', name: 'Igbo' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'fi', name: 'Suomi (Finnish)' },
  { code: 'sv', name: 'Svenska (Swedish)' },
  { code: 'no', name: 'Norsk (Norwegian)' },
  { code: 'da', name: 'Dansk (Danish)' },
  { code: 'is', name: 'Íslenska (Icelandic)' },
  { code: 'et', name: 'Eesti (Estonian)' },
  { code: 'lv', name: 'Latviešu (Latvian)' },
  { code: 'lt', name: 'Lietuvių (Lithuanian)' },
  { code: 'ga', name: 'Gaeilge (Irish)' },
  { code: 'cy', name: 'Cymraeg (Welsh)' },
  { code: 'eu', name: 'Euskara (Basque)' },
  { code: 'ca', name: 'Català (Catalan)' },
  { code: 'gl', name: 'Galego (Galician)' },
  { code: 'mt', name: 'Malti (Maltese)' },
  { code: 'az', name: 'Azərbaycan (Azerbaijani)' },
  { code: 'kk', name: 'Қазақ (Kazakh)' },
  { code: 'uz', name: 'Oʻzbek (Uzbek)' },
  { code: 'ky', name: 'Кыргызча (Kyrgyz)' },
  { code: 'tg', name: 'Тоҷикӣ (Tajik)' },
  { code: 'tk', name: 'Türkmen (Turkmen)' },
  { code: 'mn', name: 'Монгол (Mongolian)' },
  { code: 'ka', name: 'ქართული (Georgian)' },
  { code: 'hy', name: 'Հայերեն (Armenian)' },
  { code: 'az', name: 'Azərbaycan (Azerbaijani)' },
];
